version: '2'

services:
    app:
        container_name: resourcespace
        hostname: fotoarchiv
        domainname: cbjck.de
        image: dasmaeh/docker-resourcespace
        build: 
            context: ./src/docker-resourcespace
        restart: always
        ports:
            - "80"
        environment:
            VIRTUAL_HOST: "fotos.domain.tld"
            LETSENCRYPT_HOST: "fotos.domain.tld"
            LETSENCRYPT_EMAIL: "admin@domain.tld"
        depends_on: 
            - db
        links:
            - db:mysql
        external_links:
            - ldap:ldap
        networks:
            - outside
            - inside

    db:
        image: mariadb
        container_name: resourcespace-mariadb
        environment:
            MYSQL_ROOT_PASSWORD: "<My-secret-pw>"
            MYSQL_DATABASE: "resourcespace"
            MYSQL_USER: "resourcespace"
            MYSQL_PASSWORD: "<Another-secret-pw>"
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - inside


networks:
    inside:
    outside:
        external:
            name: proxy-tier

